#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${PUBSUB_PROJECT_ID}" ]]; then
  echo "Missing PUBSUB_PROJECT_ID environment variable" >&2
  exit 1
fi

if [[ -z "${PUBSUB_DESTINATION}" ]]; then
  echo "Missing PUBSUB_DESTINATION environment variable" >&2
  exit 1
fi

gcloud config set project ${PUBSUB_PROJECT_ID}

gcloud beta emulators pubsub start \
  --project=${PUBSUB_PROJECT_ID} \
  --data-dir=/opt/data \
  --host-port=${PUBSUB_DESTINATION}
